// The capture corpus's report (npm run capture:corpus writes it after the runs): docs/CAPTURE-CORPUS.md, generated from
// the records of .cache/corpus/records/ — each site's fidelity at every breakpoint (the share of pixels alike over the
// whole page, scaled by the shorter page over the longer: the study's "adjusted" figure), against the target of 98 %.
import fs from 'node:fs';
import path from 'node:path';
import type { SiteRecord } from './corpus.capture.ts';

const RECORDS = path.join('.cache', 'corpus', 'records');
const TARGET = 98;
const sites = (JSON.parse(fs.readFileSync('tools/capture/corpus.json', 'utf8')) as { sites: { id: string }[] }).sites;
const records = sites.flatMap((site) => {
  const file = path.join(RECORDS, `${site.id}.json`);
  return fs.existsSync(file) ? [JSON.parse(fs.readFileSync(file, 'utf8')) as SiteRecord] : [];
});
const widths = [...new Set(records.flatMap((one) => one.widths.map((w) => w.width)))].sort((a, b) => b - a);
const cell = (record: SiteRecord, width: number) => {
  const one = record.widths.find((w) => w.width === width);
  return one === undefined ? '—' : `${one.pixelMatchAdjusted.toFixed(1)}${one.pixelMatchAdjusted >= TARGET ? '' : ' ✗'}`;
};
const reached = records.filter((one) => one.problem === null && one.widths.length > 0 && one.widths.every((w) => w.pixelMatchAdjusted >= TARGET)).length;
const lines = [
  '# Capture corpus',
  '',
  '<!-- generated by npm run capture:corpus (tools/capture/report.ts) from .cache/corpus/records; never edited by hand -->',
  '',
  `Twenty public sites of the kinds a person captures (\`tools/capture/corpus.json\`), each recorded once into a HAR file`,
  'and replayed from it, captured by the Companion, imported with File › Import HTML, exported with File › Export, and',
  "compared with the original at every breakpoint: the share of pixels alike over the whole page (a channel within 24 of",
  `255), scaled by the shorter page over the longer. Target: ${TARGET} % at every breakpoint (STG-12.6).`,
  '',
  `Sites at the target: ${reached} of ${sites.length}. Measured: ${records.length}.`,
  '',
  `| Site | Kind | Files | Elements | ${widths.map((w) => `${w}px`).join(' | ')} | Problem |`,
  `| --- | --- | --- | --- | ${widths.map(() => '---').join(' | ')} | --- |`,
  ...records.map((one) => `| [${one.id}](${one.url}) | ${one.kind} | ${one.files} | ${one.elements ?? '—'} | ${widths.map((w) => cell(one, w)).join(' | ')} | ${one.problem ?? ''} |`),
  '',
];
fs.writeFileSync(path.join('docs', 'CAPTURE-CORPUS.md'), lines.join('\n'));
console.log(`docs/CAPTURE-CORPUS.md: ${reached} of ${sites.length} sites at ${TARGET} %, ${records.length} measured`);
